#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-jquerylib
Version  : 0.1.4
Release  : 5
URL      : https://cran.r-project.org/src/contrib/jquerylib_0.1.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/jquerylib_0.1.4.tar.gz
Summary  : Obtain 'jQuery' as an HTML Dependency Object
Group    : Development/Tools
License  : MIT
Requires: R-htmltools
BuildRequires : R-htmltools
BuildRequires : buildreq-R

%description
Most R users don't need to use this package directly, but other R packages (e.g. 'shiny', 'rmarkdown', etc.) depend on this package to avoid bundling redundant copies of 'jQuery'.

%prep
%setup -q -c -n jquerylib
cd %{_builddir}/jquerylib

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641040889

%install
export SOURCE_DATE_EPOCH=1641040889
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library jquerylib
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library jquerylib
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library jquerylib
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc jquerylib || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/jquerylib/DESCRIPTION
/usr/lib64/R/library/jquerylib/INDEX
/usr/lib64/R/library/jquerylib/LICENSE
/usr/lib64/R/library/jquerylib/Meta/Rd.rds
/usr/lib64/R/library/jquerylib/Meta/features.rds
/usr/lib64/R/library/jquerylib/Meta/hsearch.rds
/usr/lib64/R/library/jquerylib/Meta/links.rds
/usr/lib64/R/library/jquerylib/Meta/nsInfo.rds
/usr/lib64/R/library/jquerylib/Meta/package.rds
/usr/lib64/R/library/jquerylib/NAMESPACE
/usr/lib64/R/library/jquerylib/NEWS.md
/usr/lib64/R/library/jquerylib/R/jquerylib
/usr/lib64/R/library/jquerylib/R/jquerylib.rdb
/usr/lib64/R/library/jquerylib/R/jquerylib.rdx
/usr/lib64/R/library/jquerylib/help/AnIndex
/usr/lib64/R/library/jquerylib/help/aliases.rds
/usr/lib64/R/library/jquerylib/help/jquerylib.rdb
/usr/lib64/R/library/jquerylib/help/jquerylib.rdx
/usr/lib64/R/library/jquerylib/help/paths.rds
/usr/lib64/R/library/jquerylib/html/00Index.html
/usr/lib64/R/library/jquerylib/html/R.css
/usr/lib64/R/library/jquerylib/lib/1.12.4/jquery-1.12.4.js
/usr/lib64/R/library/jquerylib/lib/1.12.4/jquery-1.12.4.min.js
/usr/lib64/R/library/jquerylib/lib/1.12.4/jquery-1.12.4.min.map
/usr/lib64/R/library/jquerylib/lib/2.2.4/jquery-2.2.4.js
/usr/lib64/R/library/jquerylib/lib/2.2.4/jquery-2.2.4.min.js
/usr/lib64/R/library/jquerylib/lib/2.2.4/jquery-2.2.4.min.map
/usr/lib64/R/library/jquerylib/lib/3.6.0/jquery-3.6.0.js
/usr/lib64/R/library/jquerylib/lib/3.6.0/jquery-3.6.0.min.js
/usr/lib64/R/library/jquerylib/lib/3.6.0/jquery-3.6.0.min.map
/usr/lib64/R/library/jquerylib/lib/AUTHORS.txt
/usr/lib64/R/library/jquerylib/lib/LICENSE.txt
/usr/lib64/R/library/jquerylib/tests/testthat.R
/usr/lib64/R/library/jquerylib/tests/testthat/_snaps/jquery.md
/usr/lib64/R/library/jquerylib/tests/testthat/test-jquery.R
